In [2]:
conda install numpy


Note: you may need to restart the kernel to use updated packages.



EnvironmentNotWritableError: The current user does not have write permissions to the target environment.
  environment location: C:\ProgramData\anaconda3




Jupyter detected...
3 channel Terms of Service accepted


In [3]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [4]:
conda install numpy

Jupyter detected...
3 channel Terms of Service accepted

Note: you may need to restart the kernel to use updated packages.



EnvironmentNotWritableError: The current user does not have write permissions to the target environment.
  environment location: C:\ProgramData\anaconda3




In [5]:
conda install numpy

Jupyter detected...
3 channel Terms of Service accepted

Note: you may need to restart the kernel to use updated packages.



EnvironmentNotWritableError: The current user does not have write permissions to the target environment.
  environment location: C:\ProgramData\anaconda3




In [6]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [7]:
import numpy as np

In [8]:
#numpy array

In [9]:
my_list = [10,20,30,40]

In [11]:
type(my_list)

list

In [12]:
np.array(my_list)

array([10, 20, 30, 40])

In [13]:
my_numpy_array = np.array(my_list)

In [14]:
type(my_numpy_array)

numpy.ndarray

In [15]:
my_numpy_array

array([10, 20, 30, 40])

In [16]:
my_numpy_array[0]

np.int64(10)

In [17]:
my_numpy_array[-1]

np.int64(40)

In [18]:
my_numpy_array[0] = 100

In [19]:
my_numpy_array

array([100,  20,  30,  40])

In [20]:
#max ---> maximum ne ise onu yazdirir

In [21]:
my_numpy_array.max()

np.int64(100)

In [22]:
#min -----> minimum ne ise onu alir

In [23]:
my_numpy_array.min()

np.int64(20)

In [24]:
#mean ----> ortalamasini al

In [25]:
my_numpy_array.mean()

np.float64(47.5)

In [26]:
matrix_list = [[1,0,0] , [0,1,0] , [0,0,1], [0,0,0]]

In [27]:
type(matrix_list)

list

In [28]:
matrix_list[0][0]

1

In [29]:
numpy_matrix_list = np.array(matrix_list)

In [30]:
numpy_matrix_list

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]])

In [32]:
numpy_matrix_list[0]

array([1, 0, 0])

In [36]:
# shape sira ve kolonu gosterir
numpy_matrix_list.shape

(4, 3)

In [37]:
# arange

In [38]:
range(0,10)

range(0, 10)

In [39]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [40]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
np.arange(0,30,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [42]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [44]:
# ilk parantes shape veriyor 2. parantez tuple oluyor
# yani tuple kullanilarak yapiliyor
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [45]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [46]:
# linspace

In [47]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [48]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [49]:
#random

In [53]:
np.random.randint(1,10,3)

array([5, 8, 3], dtype=int32)

In [56]:
print(np.random.randint(1,10,3))

[3 2 9]


In [57]:
#numpy arrays methods

In [59]:
my_numpy_list = np.arange(0,20)

In [60]:
my_numpy_list

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [62]:
my_numpy_list[4]

np.int64(4)

In [63]:
my_numpy_list[4:10]

array([4, 5, 6, 7, 8, 9])

In [64]:
my_numpy_list[4:10:2]

array([4, 6, 8])

In [65]:
 my_list = list(range(0,20))

In [66]:
my_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [67]:
my_list[4:9:2]

[4, 6, 8]

In [69]:
# my_list[4:9] = -10      -----> olmuyor

In [70]:
my_numpy_list[4:9] = -10

In [71]:
my_numpy_list

array([  0,   1,   2,   3, -10, -10, -10, -10, -10,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [72]:
 other_list = np.arange(0,15)

In [73]:
other_list

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [74]:
other_list[4:10]

array([4, 5, 6, 7, 8, 9])

In [75]:
slicing_list = other_list[4:10]

In [77]:
slicing_list

array([4, 5, 6, 7, 8, 9])

In [78]:
other_list

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [79]:
slicing_list[0]

np.int64(4)

In [80]:
slicing_list[:] = 100

In [81]:
slicing_list

array([100, 100, 100, 100, 100, 100])

In [82]:
other_list

array([  0,   1,   2,   3, 100, 100, 100, 100, 100, 100,  10,  11,  12,
        13,  14])

In [83]:
 my_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [84]:
sclicing_my_list = my_list[4:9]

In [85]:
sclicing_my_list

[4, 5, 6, 7, 8]

In [86]:
sclicing_my_list = -100

In [88]:
# degismedi
my_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [89]:
numpy_list_3 = np.arange(0,20)

In [90]:
numpy_list_3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [92]:
numpy_list_3_copy = numpy_list_3.copy()

In [93]:
numpy_list_3_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [94]:
slicing_3 = numpy_list_3_copy[4:9]

In [95]:
slicing_3[:] = -100

In [96]:
slicing_3

array([-100, -100, -100, -100, -100])

In [97]:
numpy_list_3_copy

array([   0,    1,    2,    3, -100, -100, -100, -100, -100,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19])

In [98]:
numpy_list_3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [99]:
# numpy operation with numpy arrays

In [100]:
new_array = np.random.randint(1,150,25)

In [101]:
new_array

array([113, 144, 116, 112, 129,  59,  22, 131, 102,  55, 130,  64, 122,
       143,  13, 118,  90,  19,  40,  73,  75,  60,  69,   1, 116],
      dtype=int32)

In [102]:
new_array > 50

array([ True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True, False,
       False,  True,  True,  True,  True, False,  True])

In [103]:
result_array = new_array > 50

In [104]:
result_array

array([ True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True, False,
       False,  True,  True,  True,  True, False,  True])

In [105]:
new_array

array([113, 144, 116, 112, 129,  59,  22, 131, 102,  55, 130,  64, 122,
       143,  13, 118,  90,  19,  40,  73,  75,  60,  69,   1, 116],
      dtype=int32)

In [106]:
new_array[result_array]

array([113, 144, 116, 112, 129,  59, 131, 102,  55, 130,  64, 122, 143,
       118,  90,  73,  75,  60,  69, 116], dtype=int32)

In [107]:
last_array = np.arange(0,30)

In [108]:
last_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [109]:
last_array + last_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58])

In [110]:
last_array * last_array

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625,
       676, 729, 784, 841])

In [111]:
last_array - last_array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

In [112]:
last_array / last_array

C:\Users\bleas\AppData\Local\Temp\ipykernel_48524\3398326563.py:1: RuntimeWarning: invalid value encountered in divide
  last_array / last_array


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.])

In [113]:
last_array.max()

np.int64(29)

In [114]:
last_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [116]:
np.max(last_array)

np.int64(29)

In [117]:
np.min(last_array)

np.int64(0)

In [118]:
np.mean(last_array)

np.float64(14.5)

In [120]:
# sqrt ----> kare kokunu al demek
np.sqrt(last_array)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949,
       5.        , 5.09901951, 5.19615242, 5.29150262, 5.38516481])